=== MohamedAmmarAI/ITI-Power-Bi-Development-Track/xml/day 1/Lab/family.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT family (Grandfather)>
<!ELEMENT Grandfather (Father, Uncle*, Aunt*)>
<!ELEMENT Father (Mother, Daughter, Son)>
<!ELEMENT Mother (#PCDATA)>
<!ELEMENT Daughter (#PCDATA)>
<!ELEMENT Son (#PCDATA)>
<!ELEMENT Uncle (#PCDATA)>
<!ELEMENT Aunt (#PCDATA)>

<!ATTLIST Father 
          job (Engineer | Accountant | Doctor) "Engineer">
          
<!ATTLIST Daughter 
          job (Engineer | Accountant | Doctor) "Engineer"
          age NMTOKEN #REQUIRED>
          
<!ATTLIST Son 
          age NMTOKEN #REQUIRED
          sport (tennis | football) "football">
          
<!ATTLIST Aunt 
          sons NMTOKENS #IMPLIED>

=== MohamedAmmarAI/ITI-Power-Bi-Development-Track/XML/day 1/Lab/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "C:\Users\EL.DAWLIA\Desktop\family.dtd">
<family>
	<Grandfather>
		<Father job="Engineer">
			<Mother>Eman</Mother>
			<Daughter age="24" job="Doctor">Enas</Daughter>
			<Son age="30" sport="football">mohamed</Son>
		</Father>
		<Uncle>Dai</Uncle>
		<Uncle>Alaa</Uncle>
		<Aunt sons="2">sohaila</Aunt>
	</Grandfather>
</family>
