=== MohamedAmmarAI/ITI-Power-Bi-Development-Track/xml/lectureDemos/testiti.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT iti ( student )+ >
<!ELEMENT student ( id , name,email? ) >
<!ELEMENT id ( #PCDATA ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT email ( #PCDATA ) >
<!--
<!ATTLIST student track NMTOKENS #IMPLIED >
<!ATTLIST student branch (Tanta|Alex|Smart) "Tanta" >
-->
<!ATTLIST student track NMTOKENS #IMPLIED branch (Tanta|Alex|Smart) "Tanta" >

=== MohamedAmmarAI/ITI-Power-Bi-Development-Track/xml/day 1/lectureDemos/testiti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iti SYSTEM "testiti.dtd">
<iti>
    <student track="power bi">
		<id>100</id>
		<name>ahmed</name>
		<email>nasr@nasr.com</email>
	</student>
	<student>
		<id>200</id>
		<name>ali</name>
	</student>
	<student>
		<id>300</id>
		<name>omar</name>
	</student>
</iti>
